name: Publish .NET Library to NuGet

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers only on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 'netstandard2.1'  # or the version of .NET you're using

      - name: Restore dependencies
        run: dotnet restore src/AstroWatch.SpaceTrack/AstroWatch.SpaceTrack/AstroWatch.SpaceTrack.csproj

      - name: Build the project
        run: dotnet build src/AstroWatch.SpaceTrack/AstroWatch.SpaceTrack/AstroWatch.SpaceTrack.csproj --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test src/AstroWatch.SpaceTrack/AstroWatch.SpaceTrack/AstroWatch.SpaceTrack.csproj --configuration Release --no-restore --verbosity normal

      - name: Pack the NuGet package
        run: dotnet pack src/AstroWatch.SpaceTrack/AstroWatch.SpaceTrack/AstroWatch.SpaceTrack.csproj --configuration Release --no-build --no-restore --output ./nupkg

      - name: Publish to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
